### ISSUE TITLE
Move project to inbucket github organization

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket#126]
I've created a https://github.com/inbucket to own inbucket and related repos.  Will move this repo there in the future.

- [x] Update Docker build paths
- [x] Update go.mod
- [x] Update code import paths
- [x] Update README & code documentation paths
- [x] Update UI github link
- [x] Update Docker hub configuration
- [x] Update goreleaser configuration
- [x] Update https://github.com/inbucket/inbucket.org
- [x] Update wiki pages
- [x] Update other projects: enmime, fauxmailer

**Comment by jhillyerd** [comment]
Starting now: the first 3.0 beta is about ready, makes sense to do this migration before any 3.0 releases.

**Comment by jhillyerd** [comment]
This is done.  Will leave this open & pinned until April in case anyone notices anything broken.

**Comment by stephenwilliams** [comment]
I noticed that there are still some references to it from when it was under your user in the code. For example

```go
    "github.com/jhillyerd/inbucket/pkg/rest/model"
```

https://github.com/inbucket/inbucket/blob/master/pkg/rest/client/apiv1_client.go#L11

**Comment by jhillyerd** [comment]
All the changes are currently in the develop branch, pending 3.0 beta release:

https://github.com/inbucket/inbucket/blob/develop/pkg/rest/client/apiv1_client.go

I don't have any outstanding tasks prior to beta release, so it may happen this week/weekend.

**Comment by jhillyerd** [comment]
Beta1 is now merged into master, code paths should be up to date.
