### ISSUE TITLE
README still mentions etc/inbucket.conf

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket#127]
README should be updated for env variables, link to configurator.

Could also update for Go modules.

**Comment by b-lawrence** [comment]
Awesome. I'll update the copy in the README to say that and include a link to the config doc.

**Comment by b-lawrence** [comment]
For Go modules, I noticed the `go.mod` in the root of the project which simplifies things further.

After some experimentation, I was able to build `inbucket` in two easy steps.

1. Clone the repository
2. Run `go build ./cmd/inbucket` from the project root which creates the inbucket binary.

And you're set!

We might need to go further and copy the binary created by `go build` to the global bin `$PATH` so it can be run from anywhere on the user's computer.

What would be really nice is to put these steps behind one single make command -- `make install`.

Thoughts @jhillyerd?

**Comment by jhillyerd** [comment]
Not totally against the idea, but the build is a bit more complicated now in development branch; due to having to build the Elm UI.  (with nodejs installed, I think `npm ci && npm run build` does most of the work).

And with either of `master` or `develop` branches, the generated UI files need to be copied somewhere for the install.  Plus when building a distribution for github, I'm using goreleaser to cross compile and create rpm/deb files.

I've been thinking about replacing goreleaser and Makefile with Mage; but haven't spent any time on it yet.
