### ISSUE TITLE
Missing "ui/dist" directory on v3.0.0-beta1

### ISSUE THREAD

**Issue by ejDev** [inbucket/inbucket#136]
Installed inbucket following the instructions on [inbucket.org](https://www.inbucket.org/installation/from-source.html) site. But afterwards got the following error:

`> GOPATH/bin/inbucket
1:27PM INF Inbucket starting buildDate=undefined phase=startup version=undefined
1:27PM INF Retention configured for 24h0m0s module=storage phase=startup
1:27PM INF Web UI content mapped module=web path=ui/dist phase=startup
1:27PM INF SMTP listening on tcp4 addr=0.0.0.0:2500 module=smtp phase=startup
1:27PM INF POP3 listening on tcp4 addr=0.0.0.0:1100 module=pop3 phase=startup
1:27PM INF HTTP listening on tcp4 addr=0.0.0.0:9090 module=web phase=startup
1:27PM ERR Error opening file error="open ui/dist/index.html: no such file or directory" file=ui/dist/index.html module=web path=/`

Might there be a problem with the current build( v3.0.0-beta1 ) ?

**Comment by jhillyerd** [comment]
Hey, thanks for raising this.  Unlike previous versionso of Inbucket, the new UI in 3.0.0 needs to be compiled before it can be used.  If you have [npm](https://www.npmjs.com/) installed, you should be able to do the following:

```
cd ui
npm i
npm run build
```

Which will create the dist directory.  Alternately, you can grab the `ui/dist` directory from any of the release tarballs/zips: https://github.com/inbucket/inbucket/releases/tag/v3.0.0-beta1

I'll keep this bug open as a reminder to update the inbucket docs.  Let me know if you run into any problems.

**Comment by jhillyerd** [comment]
Ended up removing the from-source instructions on inbucket.org, we'll just use the inbucket/README.md for now

https://github.com/inbucket/inbucket.org/commit/7c97b0c2c45f354948fe1ea17cf09acbf9514ba5
