### ISSUE TITLE
URLs to view/download attachments from REST API are not valid

### ISSUE THREAD

**Issue by sergebug** [inbucket/inbucket#138]
When REST API https://github.com/inbucket/inbucket/wiki/REST-GET-message is used to get the message, the response contains attachment collection with two URLs. One to view attachment and one to download. Both result in 404 response when used.
view: http://{url}/mailbox/vattach/{name}/{message-id}/{file-index}/file.txt
download: http://{url}/mailbox/dattach/{name}/{message-id}/{file-index}/file.txt

Actual URL to view/download files based on the web ui appear to be the same(?) and looks like following: 
http://{url}/serve/mailbox/{name}/{message-id}/attach/{file index}/file.txt

note: actual URLs contain the extra `serve` before the mailbox and `attach` before the file index in the path and don't use vattach|dattach

**Comment by jhillyerd** [comment]
Thanks, I reworked a lot of the paths to support the single page app UI for 3.0, looks like I missed updating the APIs.
