### ISSUE TITLE
Allow a specific password to be setup for accessing POP3

### ISSUE THREAD

**Issue by MatthewJohn** [inbucket/inbucket#145]
At the moment, any password is accepted. It would be nice if an environment variable would be able to limit this.

**Comment by MatthewJohn** [comment]
If my previous work hasn't put you guys off, I would gladly do this, as we could do with this ASAP.
If so, feel free to assign to me :)

**Comment by jhillyerd** [comment]
I think that's reasonable.  I'd rather it were stored hashed in the env variable rather than plain text.  Ideally a hash with a javascript implementation, so we could add it to the configurator.

**Comment by MatthewJohn** [comment]
@jhillyerd How about SHA-512 with a user-customisable salt and hashing iterations.

Maybe use a basic implementation of: ?

    hashed_val = password + salt
    for itx in hash_iterations:
        hashed_val = sha512(hashed_val)

**Comment by MatthewJohn** [comment]
> @jhillyerd How about SHA-512 (I can only see SHA-based hashes in javascript (https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest)) with a user-customisable salt and hashing iterations.
> 
> Maybe use a basic implementation of: ?
> 
> ```
> hashed_val = password + salt
> for itx in hash_iterations:
>     hashed_val = sha512(hashed_val)
> ```

Just to clarify, for any external party reading this that, this is for the storage of the password on the server itself and if anyone were the be able to view the password (or hashed password) via this, then they most likely also have the ability the view/manipulate the emails and the container itself. The users will also be using the password in plain text (since we're not talking about any symmetric encryption) and the transport of the password via POP3 is _also_ in plain text.

**Comment by jhillyerd** [comment]
I think SHA-512 + salt is a good plan.  I think we should hard code the iterations and prefix the salt on the hash such that we only need one environment variable for this; Inbucket configuration is daunting enough for new users, I'd rather not add three.

**Comment by jhillyerd** [comment]
Please re-open if you decide to work on this again, but I don't think there is enough demand for this feature.

**Comment by MatthewJohn** [comment]
Apologies @jhillyerd , I'd completely forgotten about it - I haven't touched golang in a little while, so I'll try to remember next time I work on a golang project, so I'm prepared to take another look :D
