### ISSUE TITLE
Multiple accept domains are treated as relays

### ISSUE THREAD

**Issue by poblabs** [inbucket/inbucket#149]
When using docker on `v3.0.0-beta2-1-g12802e9, built on 2019-09-17T15:56:26+0000`, I have these options set:

```
INBUCKET_SMTP_DEFAULTACCEPT="false"
INBUCKET_SMTP_ACCEPTDOMAINS="example1.net, example2.net, example3.org"
```

inbucket will only accept mail for `example1.net`, and treats `example2.net` and `example3.org` as relays and rejects it. I assume this is unexpected behavior?

**Comment by jhillyerd** [comment]
Can you test without the spaces to see if it has an impact?  If that doesn't fix it, if you are using INBUCKET_MAILBOXNAMING="domain" can you also test with "full" or "local" and see if that impacts the result.

**Comment by poblabs** [comment]
Interesting, removing the spaces allowed `example2.net` to accept mail, but still treated `example3.org` as a relay. My mailboxnaming is on `full` and I have the acceptdomains wrapped in `"` quotes.

Also, I used the configurator to define these options. Unsure if that makes a difference, but I just copied/pasted from there.

**Comment by poblabs** [comment]
I have removed the double quotes `"` around the comma separated domains and now it appears to be working. All 3 accepted mail and others were rejected. I'll keep testing it though. Looks like the removal of spaces may have been the fix.

**Comment by jhillyerd** [comment]
What OS are you running on?  In general Unix shells will not pass on double quotes specified on the command line; they just allow you to have spaces.  If something about the way you are pasting is converting them to special quotes outside of normal ASCII (like MS Word smart quotes does), that would cause issues.

**Comment by jhillyerd** [comment]
Sometimes I prefix the command I am trying to run with echo to get an idea of what the shell is expanding things to.

**Comment by poblabs** [comment]
I've got this running on a Synology. Initially I wrapped it in quotes since it wasn't working, then didn't remove them until a few minutes ago. So I think the spaces was the real fix.

**Comment by poblabs** [comment]
Closing for now, all seems better. Will reopen if I get stuck again
