### ISSUE TITLE
I receive tons of unknown emails 

### ISSUE THREAD

**Issue by tarek369** [inbucket/inbucket#150]
can some one explain that ? this is a sample of what i recieve 

`Received: from PC-045 ([59.42.30.33]) by inbucket
  for <aa710703@yahoo.com.tw>; Sat, 18 Jan 2020 11:47:04 +0000 (UTC)
X-Originating-IP: [%RND_IP]
Authentication-Results: mta1109.mail.tp2.yahoo.com  from=gmail.com; domainkeys=neutral (no sig);  from=gmail.com; dkim=neutral (no sig)
Received: from 127.0.0.1  (EHLO n14d.bullet.sp1.yahoo.com) (%RND_IP)
  by mta1109.mail.tp2.yahoo.com with SMTP; Wed, 24 Jan 2018 10:19:04 +0000
Comment: DomainKeys? See http://antispam.yahoo.com/domainkeys
Received: from [%RND_IP] by n14.bullet.sp1.yahoo.com with NNFMP; 24 Jan 2018 10:18:36 -0000
Received: from [%RND_IP] by t14.bullet.mail.sp1.yahoo.com with NNFMP; 24 Jan 2018 10:18:35 -0000
Message-ID: <lc+zomdwfjt@eGroups.com>
User-Agent: eGroups-EW/0.82
From: =?GB2312?B?udS51Muu?= <tuuuvvwwwwwwxx@mail.in>
To: abbbc@gmail.com
Subject:
 =?GB2312?B?7ZS8iYKluOctz6zBpsq/Lc3+oJaEgjMwwaPRYiHSu9K5kfAzxa6yu8rHgvfV?=
 =?GB2312?B?ZiFmZmZn?=
Content-Type: text/html;
	charset=gb2312
Content-Transfer-Encoding: 8bit
Date: Wed, 24 Jan 2018 18:18:59 +0800
Content-Length: 309

<html>
<font size=5>
<p>美國原裝 威而鋼-犀利士-乖乖水-泰國威爾鋼果凍</p>
<p style="color: #F20; font-weight: bold;">戰神-黑神偉哥-犀力士-威爾剛30粒裝-頂級偉哥</p>
<p>女用-欲火38℃-聽話水-迷幻水-動情素-魔鬼天使-彌漫之夜-加長版</p>
<p style="color: #F16; font-weight: bold;">首頁公告那查詢 7-11取貨點   ==&gt; <a href="http://99998888son.com">http://99998888son.com</a></p>
<P align="center">&nbsp;</P>
<p>手機版情趣專區!麻倉優 粉嫩性感肉感美臀-瀧澤蘿拉-高潮名器</p>
<p style="color: #F20; font-weight: bold;">手機版情趣-性感睡衣-安全隱密 ==&gt; <a href="http://www.sex99999.com">http://www.sex99999.com</a></p>
</html>`

**Comment by jhillyerd** [comment]
It's spam.  As inbucket  accepts any mail it receives by default, it appears as an [open relay](https://en.wikipedia.org/wiki/Open_mail_relay) to spammers, despite it not actually relaying anything.

Inbucket will reject a large portion of the mail if you configure to only accept mail for your domain:

```
export INBUCKET_SMTP_DEFAULTACCEPT="false"
export INBUCKET_SMTP_ACCEPTDOMAINS="mydomain.com"
```

**Comment by tarek369** [comment]
Thanks it works now i see it blocks those emails now
