### ISSUE TITLE
Not able to open Monitor in Safari w/ basic auth

### ISSUE THREAD

**Issue by shashikiran797** [inbucket/inbucket#163]
When I open inbucket monitor page in Safari browser, I see this error in the console
WebSocket connection to 'wss://<my domain>/api/v1/monitor/messages' failed: Unexpected response code: 401

Any idea how to resolve this?

I have hosted my inbucket in AWS in docker. It works fine in Chrome

**Comment by jhillyerd** [comment]
What version of Inbucket are you running?

**Comment by jhillyerd** [comment]
Also, does this monitor work for you? http://demo.inbucket.org/monitor - that one is also running in Docker

**Comment by shashikiran797** [comment]
This is the version I'm using
Version
5c885a0, built on 2019-02-24T17:10:16+0000

http://demo.inbucket.org/monitor - this works in my Safari desktop because this doesn't have authorization.

I have enabled basic auth to connect to my server

**Comment by jhillyerd** [comment]
This is the line that generates the websocket URL: 

https://github.com/inbucket/inbucket/blob/5c885a067aa02218092a2f93398778bfcc12ef2e/ui/src/monitorMessages.js#L10

Perhaps try checking the value of `window.location.host` in the javascript console and see if it is in fact returning nothing, and also window.location to see if a value is returned from it.  I'm not sure if Safari would consider hostname sensitive info when authenticated, seems odd.

**Comment by jhillyerd** [comment]
I don't have an environment with basic auth to test this in.  Please re-open if you can gather the info requested.
