### ISSUE TITLE
Inbucket API always returns previous email instead of the latest one

### ISSUE THREAD

**Issue by govindthakur25** [inbucket/inbucket#165]
First and foremost, thank you for the awesome project.

I am using Inbucket for e2e testing using the protractor, so I have utilized the [JS Client](https://github.com/Xotabu4/inbucket-js-client) for invoking your APIs. I am calling APIs in the below order. 

```
const mailbox = await inbucketInstance.mailbox(mailBoxName); // list the Mailbox Contents: GET /api/v1/mailbox/{name}
const mailBoxId = mailbox.find((inbox) => inbox.mailbox === mailBoxName).id; // retrieve mailbox id for next API call
const email = await inbucketInstance.readEmailFrom(mailBoxName, mailBoxId); // Get Message: GET /api/v1/mailbox/{name}/{id}
```

When there are no emails in a given mailbox, my function call rightly gets the latest mail. But, if there was an email already and my function gets called, then the same code block gives me the previous email from the same mailbox, instead of the latest one. 

I have tried putting the API call inside `settimeout` (and `browser.sleep()` and other wait mechanisms ) and delay the call so that it gets enough time to read the latest email, but nothing seems to be working. So I am suggesting, there should be an API that allows us to read a specific message based on some configurable criteria, maybe timestamp or email sequence etc. 

Or am I doing it the wrong way and it is already possible with the existing APIs?

Please provide your inputs.

P.S: For a workaround, I am deleting the email as soon as I am done reading and asserting the results. :)

**Comment by jhillyerd** [comment]
I don't have direct experience with the JS API, but the messages in the `mailbox` array should arrive sorted oldest to newest.
Also, mailboxes don't have an ID other than their name, so your names/comments are not correct.

Untested, but try:

```javascript
const mailbox = await inbucketInstance.mailbox(mailBoxName);
const lastMessageId = mailbox[mailbox.length-1].id;
const email = await inbucketInstance.readEmailFrom(mailBoxName, lastMessageId);
```

**Comment by govindthakur25** [comment]
@jhillyerd Thank you for the quick response and correction in my understanding. :)
I will try this and let you know the outcome.

**Comment by govindthakur25** [comment]
Hi @jhillyerd, it worked with your approach. Thanks so much for your help, I really appreciate it.
