### ISSUE TITLE
Cant open mailbox view page using URL anymore

### ISSUE THREAD

**Issue by djamknacker** [inbucket/inbucket#171]
Before recent changes, I was able to open the mailbox view page straight away by typing the URL.
Example: 
URL/m/MAILBOX
 Right now it opens a white screen with this error in console:
`Uncaught SyntaxError: Unexpected token '<' (main.ea13ea62.js:1)`

It was super useful to use like this in test automation and will be nice if I can still use it like this. 

P.S. Inbucket is installed using the latest docker image

**Comment by jhillyerd** [comment]
Thanks, will take a look, I may have made a bad assumption somewhere when adding the configurable baseUrl.

**Comment by djamknacker** [comment]
Thx for the update.
For now, I just built docker image with the previous version of inbucket.

**Comment by jhillyerd** [comment]
For anyone else encountering this, switching to the :stable (instead of :latest) Docker hub tag will work around this issue.

It's still my top priority to fix, but will take a bit to do.

**Comment by jhillyerd** [comment]
Should now be fixed on :latest
