### ISSUE TITLE
inbucket on windows10 help request

### ISSUE THREAD

**Issue by amorley65** [inbucket/inbucket#187]
I love the simplicity of this little smtp server when running it on Windows10. But for the life of me I cant figure out how to use environment variables in it.  Specifically I am trying to start it using STARTtls. Any help or guidance would be appreciated.

**Comment by jhillyerd** [comment]
Sorry, missed this one.  The easiest way to set some environment variables and launch inbucket on windows is to write a bat script, ie create `start-inbucket.bat` in the directory that has inbucket.exe in it, with content:

```bat
set INBUCKET_SMTP_DISCARDDOMAINS="github.com"

inbucket.exe
```

Then double click on it.
