### ISSUE TITLE
Migrate off Travis-CI

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket#189]
Travis CI has been slow and buggy for months, and it appears they would like their open source users to go elsewhere: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

GitHub Actions is likely to be the best replacement.

**Comment by cpanato** [comment]
I can work on the transition, what is missing? I see there is a github actions already in place

**Comment by jhillyerd** [comment]
This is mostly done now in the develop branch.  The only piece that's missing is checking the Elm code with elm-format -- but it seems like the elm-format github actions expect elm-format to be part of the package.json deps, which doesn't work well when I'm developing under NixOS.

**Comment by jhillyerd** [comment]
I'll consider #201 as closing this, I already put the Elm stuff on the backlog project.
