### ISSUE TITLE
Disposable email not receiving emails.

### ISSUE THREAD

**Issue by angelch94** [inbucket/inbucket#195]
Hi, thanks in advance for taking your time to read this.

I have been trying to install inbucket in a vps instance in Hetzner (cloud hosting provider). The server is a ubuntu 18, i just installed docker in it and started an inbucket container using the docker command in this repository without modifying any default env config. I added an A record to my dns provider and i can verify that atleast the ui in the port 9000 is working nice atleast with HTTP (no-https). The problem is that im not receiving messages; im sending test emails from my gmail account and none of them are being listed in the monitor. 
This is the result of te logs of the docker container:

```
Installing default greeting.html to /config
{"level":"info","phase":"startup","version":"v3.0.0-rc1-2-g3c5960a","buildDate":"2020-11-19T16:20:23+0000","time":"2021-03-27T00:31:21Z","message":"Inbucket starting"}
{"level":"info","phase":"startup","module":"storage","time":"2021-03-27T00:31:21Z","message":"Retention configured for 72h0m0s"}
{"level":"info","module":"web","phase":"startup","path":"ui","time":"2021-03-27T00:31:21Z","message":"Web UI content mapped"}
{"level":"info","module":"smtp","phase":"startup","addr":"0.0.0.0:2500","time":"2021-03-27T00:31:21Z","message":"SMTP listening on tcp4"}
{"level":"info","module":"web","phase":"startup","addr":"0.0.0.0:9000","time":"2021-03-27T00:31:21Z","message":"HTTP listening on tcp4"}
{"level":"info","module":"pop3","phase":"startup","addr":"0.0.0.0:1100","time":"2021-03-27T00:31:21Z","message":"POP3 listening on tcp4"}
```
One more time, thank you for reading this!
EDIT1:
Monitor says it is Connected to the websocket. But still no messages at all.

**Comment by angelch94** [comment]
Hurray! My solution was to map the port 2500 to 25 in the host. So the docker command that works for my use case looks like this:

`docker run -d --name inbucket -p 9000:9000 -p 25:2500 -p 1100:1100 inbucket/inbucket`

Hope it helps to others in the same scenario.
Have a great day!

**Comment by jhillyerd** [comment]
You will need to configure docker to forward port 25 to 2500.

I'd recommend using the accept rules to restrict what domains inbucket accepts mail for, otherwise your server will quickly be overloaded with spam.

INBUCKET_SMTP_DEFAULTACCEPT         false                Accept all mail by default?
INBUCKET_SMTP_ACCEPTDOMAINS      yourdomainhere.com                       Domains to accept mail for

**Comment by angelch94** [comment]
> You will need to configure docker to forward port 25 to 2500.
> 
> I'd recommend using the accept rules to restrict what domains inbucket accepts mail for, otherwise your server will quickly be overloaded with spam.
> 
> INBUCKET_SMTP_DEFAULTACCEPT false Accept all mail by default?
> INBUCKET_SMTP_ACCEPTDOMAINS yourdomainhere.com Domains to accept mail for

Extremely fast response, thank you!
