### ISSUE TITLE
Current Helm Chart Seems Incompatible w/ Helm 3

### ISSUE THREAD

**Issue by akrock** [inbucket/inbucket#200]
Attempting a deployment over an existing deployment w/ the current helm chart results in the following error messages.

```
error occurred while rolling back the release. original upgrade error: cannot patch "email-inbucket" with kind Service: Service "email-inbucket" is invalid: spec.clusterIP: Invalid value: "": field is immutable: cannot patch "email-inbucket" with kind Service: Service "email-inbucket" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

This issue looks like it can be simply resolved by changing `service.yaml` to not omit the `clusterIP` property unless it is defined.
See: https://github.com/helm/helm/issues/6378#issuecomment-557746499
```
spec:
  type: "{{ .Values.service.type }}"
  {{ with .Values.service.clusterIP }} clusterIP: "{{ . }}"{{ end }}
```

Unfortunately the old helm repository for storing "all the charts" has been deprecated and they are looking for software maintainers to handle their own helm packages now, so it likely would need to be pulled over here, or into another repository under the `/inbucket` organization.

https://helm.sh/blog/charts-repo-deprecation/

**Comment by jhillyerd** [comment]
Thanks for reporting this.  I don't use k8s, so this will definitely need to be community maintained.  Do you know if there are benefits for having a dedicated repo for this? Otherwise I will create an `inbucket-community` repo to encourage contributions.

**Comment by cpanato** [comment]
I can help on that if you need help @jhillyerd

**Comment by jhillyerd** [comment]
Thanks @cpanato -- I created https://github.com/inbucket/inbucket-community and added you as a maintainer.

**Comment by cpanato** [comment]
thanks @jhillyerd I will work on the helm chart and automation this weekend

**Comment by cpanato** [comment]
initial PR: https://github.com/inbucket/inbucket-community/pull/1

sorry for the long delay

**Comment by jhillyerd** [comment]
Now that https://github.com/inbucket/inbucket-community/pull/1 is merged, is this closeable, or is there more work to be done?

**Comment by cpanato** [comment]
@jhillyerd sorry for my delay on this :( I will add the chart this week. I was busy and had not much time, apologizes

**Comment by cpanato** [comment]
PR that adds the chart is here: https://github.com/inbucket/inbucket-community/pull/2

**Comment by cpanato** [comment]
we can close this issue

you can add the inbucket helm repo: `helm repo add inbucket https://inbucket.github.io/inbucket-community`


the page: https://inbucket.github.io/inbucket-community/
