### ISSUE TITLE
LOGIN is required even with no AUTH requirements

### ISSUE THREAD

**Issue by cardonator** [inbucket/inbucket#205]
In #197, support for AUTH messages was added to Inbucket. This is great, except the implementation _requires_ auth information to be passed even if no auth information is required.

As far as I know (and definitely in congruity with public SMTP implementations such as Postfix), there is no required value of the LOGIN command or the PASSWORD command in the SMTP spec. For whatever reason, the library I'm using in Java to send SMTP requests assumes that it should pass auth information even if none is present, which causes a LOGIN to be passed with no value.

I think that inbucket should ignore empty values being passed to LOGIN and PASSWORD, if the values require testing, I think it should be added as options in the config and match the username and password to those options.

@jhillyerd if you think that change sounds good I can prepare a PR.

**Comment by jhillyerd** [comment]
This sounds like a good idea to me, thanks.

I didn't mean for #197 to go direct to `master`, so I think I will roll it back and let it live on in `develop`

**Comment by jhillyerd** [comment]
I want to fix this, but I'm having a hard time visualizing what you are describing, as I'm not very familiar with the SMTP AUTH.

Can you supply an example that is failing?

**Comment by cardonator** [comment]
No problem, I have had the best of intentions of getting to the PR but I have been really busy the past three weeks.

I basically have a java app that uses SMTP, and I am passing in empty strings to the basic auth user and password fields. In this scenario it is sending the USER and PASS commands to I bucket without any value. Prior to the PR above, that was fine because the server ignored invalid values for user and pass. Now it requires them to have a value if they are passed.

I think a simple solution is to have a setting that requires auth values to be passed, and then error if they are not passed. Withe the setting disabled it would just ignore any user and pass values.

**Comment by jhillyerd** [comment]
This should be fixed, auth login will allow empty creds now.  I tested an empty auth plain with Go's smtp client, but it still sends `AAA=` so I don't think we need to worry about that one.
