### ISSUE TITLE
Docker hub builds no longer function

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket#216]
Docker hub is eliminating their free build service.  We can either get approved as an open source project, or switch to pushing the build we already do via GitHub actions to https://hub.docker.com/

I'm leaning towards the latter.

**Comment by cpanato** [comment]
I think we can push the images to both docker and to ghcr (github).

**Comment by jhillyerd** [comment]
Ideally, I'd like to get 3.0 out the door before making changes , as I plan to drop the `develop` branch oriented "git flow" workflow, and just merge PRs into master, which will also get renamed to `main`.  This may have some impact on how we do docker builds.

**Comment by jhillyerd** [comment]
This is mostly working.  It seems the `latest` tag is not being applied for tagged releases.

Opened #231 to remind me to update the docs.

**Comment by jhillyerd** [comment]
latest tag should be fixed via #232

**Comment by jhillyerd** [comment]
Latest tag still not working :/

**Comment by cpanato** [comment]
@jhillyerd do you need any help?

**Comment by jhillyerd** [comment]
@cpanato I'd appreciate it.  Otherwise I'll read through the docs again and maybe open a question issue on docker-metadata.

**Comment by cpanato** [comment]
@jhillyerd I was able to pull the tag 3.0.0-rc4

```
 docker pull ghcr.io/inbucket/inbucket:3.0.0-rc4
3.0.0-rc4: Pulling from inbucket/inbucket
29291e31a76a: Pull complete
246800c1f096: Pull complete
db4e5237f816: Pull complete
fb26018f6359: Pull complete
b49734ff8bd0: Pull complete
08985d7448e5: Pull complete
d7f2fe23efd5: Pull complete
c41f1e7e6ad8: Pull complete
Digest: sha256:e81df2978186a2aab82fc777e9f37b56b36e503db2264c88bed40ed13f73136f
Status: Downloaded newer image for ghcr.io/inbucket/inbucket:3.0.0-rc4
ghcr.io/inbucket/inbucket:3.0.0-rc4
```

so I don't know what is missing or wrong

**Comment by jhillyerd** [comment]
Sorry, so the individual build version tags are working, but we should be applying a `latest` tag to any tagged release, and an `edge` tag to development releases.

The edge tag is working, but so far I haven't been able to trigger a latest tag.  Perhaps it will only trigger on a v0.0.0 style release with no -rc or-beta suffix, but I'm not sure how to validate it without setting up a whole new GH repo to test.

**Comment by jhillyerd** [comment]
I was able to push a tag manually for the Aug 22 build, so at least this isn't a release blocker, and hopefully with the latest tag we can get a bit of test mileage before blessing rc4 as 3.0.0

**Comment by jhillyerd** [comment]
Ok, latest did appear w/ the 3.0.0 release, so I think the meta generator doesn't tag prereleases, which is probably fine.
