### ISSUE TITLE
Publish tagged docker images

### ISSUE THREAD

**Issue by cpanato** [inbucket/inbucket#222]
Publish tagged dockers images like `inblucket:v3.0.0` and not only `inbucket:stable` 

in the inbucket helm charts and in any docker deployment will be good to use immutable tags to avoid possible issues/breaks

**Comment by jhillyerd** [comment]
#228 should now do this for us, but we won't know until the next release.

**Comment by jhillyerd** [comment]
Turns out it did not work, but I've made one more tweak and confirmed we have tags on DH and GHCR
