### ISSUE TITLE
IP address instead of domain name in RCPT TO

### ISSUE THREAD

**Issue by LubosD** [inbucket/inbucket#243]
Hello,

I'm trying to integrate Inbucket into my e2e tests.

The dynamically instantiated VM where Inbucket would run doesn't get a domain name for its public IP address (argh), so my idea was to try out whether I could have my test e-mails sent to `somebody@IP_ADDRESS` rather than bother with no-ip and such.

I don't want to have the tested application send e-mails directly to Inbucket, but rather via Mailjet (which we use) so that the test is a little more realistic.

Now the thing is that the correct format according to the RFC is `somebody@[123.123.123.123]`. This format is accepted by Postfix and all SMTP servers I have access to.

Inbucket, however, rejects this format and only accepts `somebody@123.123.123.123`, which is not accepted by anyone else, so it's unusable.

```
<testtest@[130.61.201.XXX]>: host 130.61.201.XXX[130.61.201.XXX] said: 501 Bad
    recipient address syntax (in reply to RCPT TO command)
```

Do you think you could extend your domain part validation code to support this syntax?

**Comment by jhillyerd** [comment]
Yes, I think this should be considered a bug if it's in common use.  I don't plan to be doing much work on Inbucket in the next few months.

If you or someone else is interested in submitting a PR, I'd start by looking at:

* https://github.com/inbucket/inbucket/blob/master/pkg/server/smtp/handler.go#L436
* https://github.com/inbucket/inbucket/blob/master/pkg/server/smtp/handler_test.go#L230

**Comment by jhillyerd** [comment]
Slightly more challenging to fix than I'd hoped.  The syntax for RCPT TO: is the `forward-path` in https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.2

Go's address parser does not like the IP syntax, but we may be able to use our own exiting parser for this.

TBD how this impacts full and domain addressing modes.
