### ISSUE TITLE
Support rejecting/dropping mail based on From domain

### ISSUE THREAD

**Issue by writetoyogi** [inbucket/inbucket#245]
Hello Sir,

I'm trying to get rid of the emails outside of gmail domain by configuring below options in inbucket.service file at path /etc/systemd/system/multi-user.target.wants# however the emails outside gmail domain keeps coming.

INBUCKET_SMTP_DEFAULTACCEPT="false"
INBUCKET_SMTP_ACCEPTDOMAINS="gmail.com"

Version Used - inbucket_2.1.0_linux_amd64.deb

Please can you suggest to help me out. Thanks !

**Comment by jhillyerd** [comment]
It's not clear from your example if you are setting them correctly with systemd, the file should have lines like:

```
[Service]
Environment=INBUCKET_SMTP_DEFAULTACCEPT=false
Environment=INBUCKET_SMTP_ACCEPTDOMAINS=gmail.com
```

Also, please note that the accept domains in inspecting the To address domain, not the From address domain.

Hope that helps.

**Comment by writetoyogi** [comment]
Thanks @jhillyerd for your response!

I missed to mention it correctly in the issue however we have set it as you dictated above with systemd.

Is there any way we can inspect ‘from’ address domain since we want to control the spam traffic hitting the mailbox?

**Comment by jhillyerd** [comment]
No, unfortunately Inbucket doesn't have a way to filter by from domain.  In the past I had planned on building a companion server that would make it easier to route (and blackhole) dev/test email, but I don't work with email in my day job anymore, so I don't have a need for it.  

I've converted this issue into a feature request, as I don't think it would be too complicated to add to Inbucket itself.  It's not likely I will work on this anytime soon, so you may want to find another solution in the meantime.  You may be able to accomplish this by putting a traditional email server (Postfix, etc) in-front of Inbucket and telling that server to use your Inbucket IP as a smart relay.

**Comment by writetoyogi** [comment]
Sure ! This will be really useful. Thank you for your help @jhillyerd 👍🏻

**Comment by cyd01** [comment]
Hi
I've proposed a little PR to add this requested feature: https://github.com/inbucket/inbucket/pull/375

**Comment by jhillyerd** [comment]
Thanks, will take a look next week

**Comment by jhillyerd** [comment]
available in beta2
