### ISSUE TITLE
Builds for arm and arm64

### ISSUE THREAD

**Issue by adrium** [inbucket/inbucket#246]
I am running inbucket on a Raspberry Pi. As such, it would be useful to provide arm and arm64 binaries as well. (Even though it is very easy to cross-compile).

**Comment by jhillyerd** [comment]
This is a good idea.  I'm not sure when I'll get around to trying it out, but the builds are done with goreleaser, config @ https://github.com/inbucket/inbucket/blob/master/.goreleaser.yml if you feel like taking a crack at it.

**Comment by adrium** [comment]
Thanks for your quick response.
Unfortunately, I am not familiar with goreleaser, so I don't know about any caveats when simply adding `arm64` to the `goarch` list... :man_shrugging:

However, there were no issues at all cross-compiling the project on an `amd64` Ubuntu:

    $ GOARCH=arm64 go build ./cmd/inbucket

**Comment by danielsimkus** [comment]
Hi, I could really use this too 👍  Hopefully it is just a case of adding arm64 to the goarch array

**Comment by jhillyerd** [comment]
It looks like we are building arm 6 (I think this was the default with goreleaser) right now.  I found this:

> The RasPis have an ARM CPU running in 32 bit mode under Linux. Pi1 is ARM6, Pi2 and 3 are ARM7, Pi4 is ARM8. However, commonly distributed OSs like Raspbian are still ARM7 in 32 bit mode. 

I would imagine most folks trying to run Inbucket would have a Pi2 or newer?  Even Pi3 was the first one that wasn't miserably slow for me.

**Comment by adrium** [comment]
Yes, I think it makes sense to only support armv7 (for raspbian) and arm64 (for ubuntu). I have two raspis with those OSes and can try the builds.

**Comment by jhillyerd** [comment]
Alright, https://github.com/inbucket/inbucket/releases/tag/v3.0.1-rc2 is out, and has packages for arm, let me know if it worked. :)

**Comment by adrium** [comment]
The Linux builds work:

```
$ uname -srm
Linux 5.10.63-v7l+ armv7l
$ ./inbucket_3.0.1-rc2_linux_armv7/inbucket
12:22AM INF Inbucket starting buildDate=2022-01-24T01:47:42Z phase=startup version=3.0.1-rc2

$ uname -srm
Linux 5.11.0-1023-raspi aarch64
$ ./inbucket_3.0.1-rc2_linux_arm64/inbucket
12:23AM INF Inbucket starting buildDate=2022-01-24T01:47:42Z phase=startup version=3.0.1-rc2
```

Thanks a lot!
