### ISSUE TITLE
index.html missing in RPM, deb, tarball packages

### ISSUE THREAD

**Issue by djenniex-bene** [inbucket/inbucket#249]
I still see the error 'Failed to parse HTML template' which was fixed in a previous ticket (https://github.com/inbucket/inbucket/issues/204). The installation process I used was via the RPM.

During the Systemd startup, I see the error in the journal:
```
Jan 17 17:40:16 inbucket[15129]: 5:40PM ERR Failed to parse HTML template error="open /usr/local/share/inbucket/ui/index.html: no such file or directory" cwd=/ module=web path=/usr/local/share/inbucket/ui/index.html phase=startup
```

There is an npm-debug log in the ui directory stating the the npm build commands 
```
[/usr/local/share/inbucket/ui]# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose stack Error: ENOENT: no such file or directory, open '/usr/local/share/inbucket/ui/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /usr/local/share/inbucket/ui
6 error Linux 4.14.256-197.484.amzn2.x86_64
7 error argv "/usr/bin/node" "/bin/npm" "run" "build"
8 error node v6.17.1
9 error npm  v3.10.10
10 error path /usr/local/share/inbucket/ui/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/usr/local/share/inbucket/ui/package.json'
15 error enoent ENOENT: no such file or directory, open '/usr/local/share/inbucket/ui/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
````

**Comment by jhillyerd** [comment]
Yikes.  Thanks for the log, this is with the current 3.0 release RPM?

**Comment by djenniex-bene** [comment]
Yes, I currently have the version installed via yum

```
# yum list installed | grep inbucket
inbucket.x86_64                       3.0.0-1                        installed
```

**Comment by jhillyerd** [comment]
I'm not seeing that npm-debug log in the official inbucket RPM, so I suspect your rpm is being built by someone else.

However, my rpm is also missing the index.html.  Testing on my machine, it looks like the index.html is being generated but not included in the release artifacts.  Will see if I can fix it.

**Comment by jhillyerd** [comment]
Will keep this open until I've cut a new release

**Comment by jhillyerd** [comment]
Ok, I believe I've fixed this.  I also went ahead and updated Go and JavaScript dependencies as there were some security advisories out for what we were using in 3.0.0.  If you get the chance, please download the RPM from our releases page and let me know if the issue is resolved.  I don't have a RPM based VM setup to test on right now.

https://github.com/inbucket/inbucket/releases/tag/v3.0.1-rc1

**Comment by jhillyerd** [comment]
Tested packages:

- [ ] tar.gz
- [ ] deb
- [ ] rpm
