### ISSUE TITLE
Won't send greeting in kubernetes

### ISSUE THREAD

**Issue by tusciucalecs** [inbucket/inbucket#272]
Hello,

I have used inbucket deployed in docker many times before.
I have a very specific case where the smtp handshake fails. 
The problem happens when having a kubernetes with docker deployment and the nodejs client (nodemailer) tries to do the smtp handshake. 
After the connection is established, inbucket won't send the initial greeting.
I was able to reproduce the problem with telnet.
If I do a port-forward from local to inbucket container and open the connection by running telnet on local I receive the greeting.
If I run the telnet command inside a docker container running in kubernetes I don't receive the greeting from inbucket unless I initiate the discussion.

Please check the screenshot.
<img width="461" alt="smtp telnet" src="https://user-images.githubusercontent.com/4602287/167267192-1ad5fb52-257b-4cd4-a56f-c47d80681d82.png">

Thanks,
Alecs

**Comment by jhillyerd** [comment]
This seems like something might be proxying the connection and not forwarding it to inbucket until it has seen some data.  I don't use k8s so I can't help debug that aspect.

Can you check if there is anything interesting in the inbucket log output prior to you sending anything?

**Comment by tusciucalecs** [comment]
Thanks for the tip. 
You are right.
I also found [this issue ](https://github.com/istio/istio/issues/10832)

**Comment by jhillyerd** [comment]
Kinda funny, I just ran into this exact same issue with nomad + traefik... so it's not exlcusive to k8s + istio.
