### ISSUE TITLE
Issue receiving email from Windows Defender

### ISSUE THREAD

**Issue by 9072997** [inbucket/inbucket#283]
Here is a conversation between an MTA (I've been told this is "Windows Defender mail protection", but I don't know much about the remote system) and inbucket:
```smtp
220 bitbucket.bentonvillek12.org Inbucket SMTP ready
EHLO GCC02-BL0-obe.outbound.protection.outlook.com
250-Great, let's get this show on the road
250-8BITMIME
250-AUTH PLAIN LOGIN
250 SIZE 10240000
MAIL FROM:<bounces+SRS=Nsvoo=YB@arkdhs.onmicrosoft.com> SIZE=38677 AUTH=<>
501 Was expecting MAIL arg syntax of FROM:<address>
QUIT
```
![image](https://user-images.githubusercontent.com/1310772/181628568-3f9d8cf7-c4f8-4ad6-ab67-71c4dec33de8.png)

I don't know enough about SMTP to know who broke protocol here, but the remote system is in production use and sending many emails a day, so I'm guessing inbucket made the mistake.

**Comment by jhillyerd** [comment]
Thanks, this looks like an inbucket bug, our FROM parsing regex can only handle a single parameter.

https://github.com/inbucket/inbucket/blob/main/pkg/server/smtp/handler.go#L60

**Comment by jhillyerd** [comment]
Looks like it was actually the `<>`, not multiple parameters that was the issue.

**Comment by 9072997** [comment]
It looks like that fixed the original example, but I have another closely related one. This is with v3.0.3, which I believe is after the patch.
![image](https://user-images.githubusercontent.com/1310772/185493017-4984f813-f8e6-46ec-8065-5c6c9b98d25c.png)
```
220 bitbucket.bentonvillek12.org Inbucket SMTP ready
EHLO GCC02-DM3-obe.outbound.protection.outlook.com
250-Great, let's get this show on the road
250-8BITMIME
250-AUTH PLAIN LOGIN
250 SIZE 10240000
MAIL FROM:<bounces+SRS=gdEYy=YW@arkdhs.onmicrosoft.com> SIZE=25475 AUTH=<> BODY=7BIT
501 Was expecting MAIL arg syntax of FROM:<address>
QUIT
```

**Comment by jhillyerd** [comment]
Do you have the ability to test against the main branch (ie Docker hub `edge` tag?)  It would be nice to know if this is truly fixed before cutting another release.

**Comment by 9072997** [comment]
Yes, but I'm not back in the office until Tuesday, so it will have to wait until then.

**Comment by jhillyerd** [comment]
Excellent, no rush, thanks!

**Comment by 9072997** [comment]
It looks like that worked with 547a12f. Thanks.
![image](https://user-images.githubusercontent.com/1310772/188733868-cb13a99d-0898-4855-a120-8800a4d33ba8.png)
