### ISSUE TITLE
Reject specific local parts of mail addresses

### ISSUE THREAD

**Issue by nagraskal** [inbucket/inbucket#358]
Hi
first of all thank you for this great tool! I use it in a somewhat production style for my login user addresses, it enables me to have a different address every time I need one (accounts, mailing lists etc.) and to hide my private mail address.
but as you might expect, some sites "loose" there addresses to spammers or worse, and I have to change these addresses. because I use the same domain-part for every address, I'd like to have the possibility to reject mails by the local part of the address ( the "user" part in "user@domain.com" ).
I've already written a small patch which adds a "DiscardDomains" config setting, and updated the policy/address.go and recipient.go, and its running  flawlessly.
It would be great to have this features upstreamed!

thanks again for your great work!

**Comment by jhillyerd** [comment]
Thanks for the kind words.

As of the current beta, Inbucket should be able to accomplish this via scripting, see an example here: https://github.com/inbucket/inbucket/wiki/Lua-Examples#event-trigger-before-mail-accepted

I expect scripting to evolve some as I receive feedback on it, and add more features.  Let me know if you get a chance to test it.

If your patch is simple enough, I will also consider including it -- but my goal for scripting is to prevent the need to add a bunch more config options for edge cases.

**Comment by nagraskal** [comment]
Thank you for your answer. I will test if I get it to work via scripting - if not I will submit my patch, its only about 15 lines added/changed plus documentation.

**Comment by andreafa** [comment]
Hello,
I have a similar need: filter incoming emails based on the recipient's address (to:).

Lua Example "[Event trigger: before mail accepted](https://github.com/inbucket/inbucket/wiki/Lua-Examples#event-trigger-before-mail-accepted)" works fine on the sender email address (from:).

Is there a way to make it work for the recipient's email address?
(the INBUCKET_SMTP_ACCEPTDOMAINS variable is limited to the domain part only)

**Comment by jhillyerd** [comment]
@andreafa there is not currently a way to do what you want, I plan to add more ways to interact with inbound  mail (like a before message stored event that could prevent it from being written to disk)

**Comment by jhillyerd** [comment]
@andreafa I've added the inbucket.before.message_stored event, it can be used to remap or drop mail for certain mailboxes, see example: https://github.com/inbucket/inbucket/wiki/Lua-Examples#event-trigger-before-message-stored

**Comment by jhillyerd** [comment]
available in beta2
