### ISSUE TITLE
Securing the entire solution

### ISSUE THREAD

**Issue by IdiotWithGuns** [inbucket/inbucket#361]
Hello,

Loving the inbucket and its doing exactly what I am looking to do.
Is there a way to secure the environment so that we can have a area that is protected via password or a token?

Thank you,

**Comment by jhillyerd** [comment]
Nothing built in, but you can put Inbucket behind a reverse proxy (nginx, traefik, or even apache) to control access.  See https://github.com/inbucket/inbucket/issues/96#issuecomment-386927027 for an nginx config that might get you started.
