### ISSUE TITLE
POP3 lacks TLS support

### ISSUE THREAD

**Issue by bimargulies-google** [inbucket/inbucket#378]
I'm writing this issue to discover whether you are open to a contribution adding TLS to POP3. If so, I will (probably) offer a contribution.

**Comment by jhillyerd** [comment]
Sure, I think that would be a helpful addition, thanks!  You might be able to use #98 as a reference.

**Comment by bimargulies-google** [comment]
I've coded this, but I'm a but puzzled about testing.  I guess I'll try adding a pop test.

**Comment by bimargulies-google** [comment]
The lack of a session struct in POP complicates testing a bit. If all I do is add testing for TLS, it's not too bad, but setting up the same kind of testing architecture will be harder.

**Comment by bimargulies-google** [comment]
oh, ignore me.

**Comment by jhillyerd** [comment]
Implemented in #384
