### ISSUE TITLE
Cannot set INBUCKET_STORAGE_PARAMS=path:D:\anything causes error

### ISSUE THREAD

**Issue by tqangxl** [inbucket/inbucket#399]
D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS=D:\Lib\OS_Software\inbucket_3.1.0\maildata\

D:\Lib\OS_Software\inbucket_3.1.0>.\inbucket.exe
5:31PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:31PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:31PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS= 'D:\Lib\OS_Software\inbucket_3.1.0\maildata\'

D:\Lib\OS_Software\inbucket_3.1.0>.\inbucket.exe
5:32PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:32PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:32PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS="D:\Lib\OS_Software\inbucket_3.1.0\maildata\"

D:\Lib\OS_Software\inbucket_3.1.0>.\inbucket.exe
5:32PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:32PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:32PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>inbucket.exe
5:33PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:33PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:33PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>inbucket.exe
5:33PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:33PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:33PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS=".\maildata\"

D:\Lib\OS_Software\inbucket_3.1.0>inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting '".\maildata\"' to type map[string]string. details: invalid map item: "\".\\maildata\\\""

D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS= 'D:\\Lib\\OS_Software\\inbucket_3.1.0\\maildata\\'

D:\Lib\OS_Software\inbucket_3.1.0>inbucket.exe
5:34PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:34PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:34PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>set INBUCKET_STORAGE_PARAMS="D:/Lib/OS_Software/inbucket_3.1.0/maildata/"

D:\Lib\OS_Software\inbucket_3.1.0>inbucket.exe
5:35PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:35PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:35PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OS_Software\inbucket_3.1.0>nssm.exe edit mail-svr-inbucket

D:\Lib\OS_Software\inbucket_3.1.0>nssm.exe remove mail-svr-inbucket
Service "mail-svr-inbucket" removed successfully!

D:\Lib\OS_Software\inbucket_3.1.0>cd ..

D:\Lib\OS_Software>cd ..

D:\Lib>cd OSSoftware

D:\Lib\OSSoftware>
D:\Lib\OSSoftware>cd inbucket

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildata\"

D:\Lib\OSSoftware\inbucket>inbucket
5:39PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:39PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:39PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildatafile"

D:\Lib\OSSoftware\inbucket>inbucket
5:40PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
5:40PM INF Script file not found module=lua path=inbucket.lua phase=startup
5:40PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_TYPE= file

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS= path:"D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_RETENTIONPERIOD=0

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_MAILBOXMSGCAP=0

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting ' path:"D:\Lib\OSSoftware\inbucket\maildata"' to type map[string]string. details: invalid map item: " path:\"D:\\Lib\\OSSoftware\\inbucket\\maildata\""

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS= path:D:\Lib\OSSoftware\inbucket\maildata

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting ' path:D:\Lib\OSSoftware\inbucket\maildata' to type map[string]string. details: invalid map item: " path:D:\\Lib\\OSSoftware\\inbucket\\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS= path:".\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_RETENTIONPERIOD to RetentionPeriod: converting '0 ' to type time.Duration. details: time: unknown unit " " in duration "0 "

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS= path:D:\Lib\OSSoftware\inbucket\maildata

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_RETENTIONPERIOD="0"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_MAILBOXMSGCAP="0"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting ' path:D:\Lib\OSSoftware\inbucket\maildata' to type map[string]string. details: invalid map item: " path:D:\\Lib\\OSSoftware\\inbucket\\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_TYPE= "file"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting ' path:D:\Lib\OSSoftware\inbucket\maildata' to type map[string]string. details: invalid map item: " path:D:\\Lib\\OSSoftware\\inbucket\\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS= path:"D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting ' path:"D:\Lib\OSSoftware\inbucket\maildata"' to type map[string]string. details: invalid map item: " path:\"D:\\Lib\\OSSoftware\\inbucket\\maildata\""

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_RETENTIONPERIOD to RetentionPeriod: converting '"0"' to type time.Duration. details: time: invalid duration "\"0\""

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_TYPE= file

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=D:\Lib\OSSoftware\inbucket\maildata

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_RETENTIONPERIOD=0

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_MAILBOXMSGCAP=0

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:01PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:01PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:01PM FTL Fatal error during startup error="unknown storage type configured: \" file\"" phase=startup

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_TYPE=file

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:01PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:01PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:01PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:D:\Lib\OSSoftware\inbucket\maildata

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting 'path:D:\Lib\OSSoftware\inbucket\maildata' to type map[string]string. details: invalid map item: "path:D:\\Lib\\OSSoftware\\inbucket\\maildata"

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:"D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting 'path:"D:\Lib\OSSoftware\inbucket\maildata"' to type map[string]string. details: invalid map item: "path:\"D:\\Lib\\OSSoftware\\inbucket\\maildata\""

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:03PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:03PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:03PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:04PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:04PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:04PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:"D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting 'path:"D:\Lib\OSSoftware\inbucket\maildata"' to type map[string]string. details: invalid map item: "path:\"D:\\Lib\\OSSoftware\\inbucket\\maildata\""

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:D:\Lib\OSSoftware\inbucket\maildata

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting 'path:D:\Lib\OSSoftware\inbucket\maildata' to type map[string]string. details: invalid map item: "path:D:\\Lib\\OSSoftware\\inbucket\\maildata"

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="path:D:\Lib\OSSoftware\inbucket\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
Configuration error: envconfig.Process: assigning INBUCKET_STORAGE_PARAMS to Params: converting '"path:D:\Lib\OSSoftware\inbucket\maildata"' to type map[string]string. details: invalid map item: "\"path:D:\\Lib\\OSSoftware\\inbucket\\maildata\""

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="path:.\maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:08PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:08PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:08PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="path:maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:09PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:09PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:09PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="path:.\maildata"

D:\Lib\OSSoftware\inbucket>
D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS="path:/maildata"

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:11PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:11PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:11PM FTL Fatal error during startup error="'path' parameter not specified" phase=startup

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:maildata

D:\Lib\OSSoftware\inbucket>set INBUCKET_STORAGE_PARAMS=path:/maildata

D:\Lib\OSSoftware\inbucket>.\inbucket.exe
6:12PM INF Inbucket starting buildDate=2023-02-28T19:12:04Z phase=startup version=3.1.0-beta1
6:12PM INF Script file not found module=lua path=inbucket.lua phase=startup
6:12PM INF Web UI content mapped module=web path=ui/dist phase=startup
6:12PM INF Retention scanner disabled module=storage phase=startup
6:12PM INF HTTP listening on tcp4 addr=0.0.0.0:9000 module=web phase=startup
6:12PM INF SMTP listening on tcp4 addr=0.0.0.0:2500 module=smtp phase=startup
6:12PM INF POP3 listening on tcp4 addr=0.0.0.0:1100 module=pop3 phase=startup
6:15PM INF Received SIGINT, shutting down phase=shutdown signal=SIGINT

**Comment by jhillyerd** [comment]
I took a look, and the library we use to parse environment variables cannot handle a colon inside a map value.  I think we'll need to update Inbucket to accept some sort of alternate syntax for windows paths that include drive letters.

**Comment by jhillyerd** [comment]
Looking at some alternative config parsers:

* env would fail in the same way: https://github.com/caarlos0/env/blob/main/env.go#L547
* viper would require the env variable to be in JSON format, which is a mess IMO

**Comment by jhillyerd** [comment]
Once beta2 is published, you will be able to use powershell:

```powershell
set-item env:INBUCKET_STORAGE_TYPE file
set-item env:INBUCKET_STORAGE_PARAMS "path:D$\inbucket"
```

or cmd.exe: `set INBUCKET_STORAGE_PARAMS="path:D$\inbucket"`
