### ISSUE TITLE
INBOX should be case-insensitive

### ISSUE THREAD

**Issue by bimargulies-google** [inbucket/inbucket#410]
The RFC specifically says that the string INBOX should be treated case-insensitively. If I create a mailbox named 'Inbox', and attempt to access it via the name INBOX, it isn't found. Now, that first step might be a foot-canon, but perhaps we want to canonicalize that name when creating a new mailbox?

**Comment by jhillyerd** [comment]
Off the top of my head, I can't think of any reason we shouldn't do this -- but I'd propose its introduced as a default-disabled option.  It could later be default-enabled during a major release.

**Comment by jhillyerd** [comment]
Poking around a bit, I think Inbucket is already trying to normalize to lower case, ie https://github.com/inbucket/inbucket/blob/main/pkg/policy/address.go#L367

And I am able to access with uppercase via the webui, http://demo.inbucket.org/m/RUTH/

So this is probably a bug, what access method are you using?

**Comment by bimargulies-google** [comment]
I called  mbx, err := user.GetMailbox(mb.GetName())

with "Inbox"

**Comment by bimargulies-google** [comment]
I am sorry to report that I put this bug in the wrong place altogether. It relates to IMAP, which isn't in inbucket. I should have posted it in go-imap.
