### ISSUE TITLE
docker: Clarify discard domain vs other domains on Welcome page

### ISSUE THREAD

**Issue by PutziSan** [inbucket/inbucket#437]
Hi,

I've noticed a small issue on the default start page. It mentions **@bitbucket.local** for testing, but it seems like it should be **@inbucket.local**. Using **@bitbucket.local** didn't work in my tests. I'm attaching a screenshot for reference. Is this a typo, or am I missing something?

![Screenshot from 2023-11-16 14-12-12](https://github.com/inbucket/inbucket/assets/13392042/9458dcfa-9ccb-4bc6-9a3c-27a9e154be79)

Further info: I noticed the `@bitbucket.local` domain here https://github.com/inbucket/inbucket/blob/main/etc/dev-start.sh

**Comment by jhillyerd** [comment]
It depends on your goal, if you want to view the messages sent, then inbucket.local is good (along with just about any other domain); messages sent to bitbucket.local are accepted, but *not stored*, so you can never see them.

For more context, I added this `INBUCKET_SMTP_DISCARDDOMAINS` feature when I was helping to do a 24 hour soak test of a large service; during the test the service needed to send thousands of emails a minute, but we weren't interested at looking at them individually, just seeing the ballpark delivery numbers on the Inbucket Status page was enough.  At those delivery volumes, Inbucket was able to store the messages, but the expiration process could not keep up with the deletions and we'd run out of disk space.

I think I can reword that welcome page to be more clear, so will treat this as a bug.
