### ISSUE TITLE
Use options for client.New

### ISSUE THREAD

**Issue by corey-aloia** [inbucket/inbucket#462]
Currently client.New only supports setting the base url. I would imagine that there are more options possible in the future, plus some already that I would like to use.

Currently, I would like to be able to create a transport object so that I can use tls auth.

Example code change:
```
type ClientOpts struct {
	BaseUrl   string
	Timeout   time.Duration
	Transport http.RoundTripper
}

// creates a new clientOpts given the base URL of an Inbucket server, ex:
// "http://localhost:9000
func NewClientOpts(BaseUrl string) *ClientOpts {
	return &ClientOpts{
		Timeout: 30 * time.Second,
	}
}

func (c *ClientOpts) WithTransport(transport http.RoundTripper) *ClientOpts {
    c.Transport = transport
    return c
}

// New creates a new v1 REST API c lient given the base URL of an Inbucket server, ex:
// "http://localhost:9000"
func New(opts *ClientOpts) (*Client, error) {
	parsedURL, err := url.Parse(opts.BaseUrl)
	if err != nil {
		return nil, err
	}
	c := &Client{
		restClient{
			client: &http.Client{
				Timeout: opts.Timeout,
				Transport: opts.Transport,
			},
			baseURL: parsedURL,
		},
	}
	return c, nil
}
```

So I could then do:
```
    cert, err := tls.LoadX509KeyPair("Client.pem", "Client.key")

    tlsConfig := &tls.Config{
        Certificates:       []tls.Certificate{cert},
        RootCAs:            caCertPool,
        InsecureSkipVerify: false,
    }
    clientOpts:= NewClientOpts("https://my-ingress.secure.api.com").WithTransport(&http.Transport{TLSClientConfig: tlsConfig})
     
    client := client.New(clientOpts)
```

I looked at adding the `WithTransport` to the restClient directly, but it looks like this uses a custom interface instead of http.client directly, making it not possible to adjust the Transport property, hence doing it at creation time

Or maybe there is already a way to use tlsAuth with an inbucket client?

If what I write sounds reasonable then I can open a PR. I haven't quite tried locally, but I can create a fork and make sure it works

**Comment by jhillyerd** [comment]
Yes, the Inbucket rest client definitely could use some work.  :)  I like the idea of adding options to it, but we need to maintain backwards compat on the New function.  We did this in my enmime project by using `...` to accept a list of options to apply.  This pattern also hides the "option struct" from the public API, allowing it to be modified.

```go
// this holds the set option values
type Parser struct {
	skipMalformedParts              bool
    // ... more
}

func NewParser(ops ...Option) *Parser {
	p := Parser{}

	for _, o := range ops {
		o.apply(&p)
	}

	return &p
}

// Option to configure parsing.
type Option interface {
	apply(p *Parser)
}

// SkipMalformedParts sets parsing to skip parts that's can't be parsed.
func SkipMalformedParts(s bool) Option {
	return skipMalformedPartsOption(s)
}

type skipMalformedPartsOption bool

func (o skipMalformedPartsOption) apply(p *Parser) {
	p.skipMalformedParts = bool(o)
}
```

see:

https://github.com/jhillyerd/enmime/blob/main/parser.go
https://github.com/jhillyerd/enmime/blob/main/options.go

**Comment by corey-aloia** [comment]
@jhillyerd good idea! That actually reminded me of a different library I use which does the same thing, but has a slightly different way of doing it. Here is a draft PR to demonstrate: 
https://github.com/inbucket/inbucket/pull/463

I think it is a bit more straightforward having as a function vs using apply. Let me know what you think 👍 
For setters you return a function, for boolean you just pass the function like:
```
inbucketClient, err = client.New(restBaseURL,
			client.WithClientOptsTransport(&http.Transport{TLSClientConfig: tlsConfig}),
			client.WithClientOptsNoFollowRedirects))
```

**Comment by jhillyerd** [comment]
BTW, I made one small naming change after your PR `WithOptTransport` is now `WithTransport` via #464
