### ISSUE TITLE
inbucket unit exited after WRN Wasn't expecting STLS here module=pop3

### ISSUE THREAD

**Issue by dongshan3** [inbucket/inbucket#515]
Sir, I started inbucket(installed using inbucket_3.1.0-beta2_linux_amd64.deb package) via systemd on debian 12 OS. inbucket unit exited after some minutes. I got these log from `journalctl -xu inbucket --no-pager`

> Jun 12 09:43:23 mail.poste.demo.example.comp systemd[1]: Starting inbucket.service - Inbucket Disposable Email Service...
      Subject: A start job for unit inbucket.service has begun execution
      Defined-By: systemd
      Support: https://www.debian.org/support
      A start job for unit inbucket.service has begun execution.
      The job identifier is 3695.
Jun 12 09:43:23 mail.poste.demo.example.comp systemd[1]: Started inbucket.service - Inbucket Disposable Email Service.
      Subject: A start job for unit inbucket.service has finished successfully
      Defined-By: systemd
      Support: https://www.debian.org/support    
      A start job for unit inbucket.service has finished successfully.    
      The job identifier is 3695.
Jun 12 09:46:18 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/.git/config proto=HTTP/1.1 remote=[::1]:52520
Jun 12 09:46:31 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/server proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:31 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/.vscode/sftp.json proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:31 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/about proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:31 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/debug/default/view?panel=config proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/v2/_catalog proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/server-status proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/login.action proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/_all_dbs proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/.DS_Store proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/.env proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/.git/config proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:32 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/s/7393e2632313e2237313e2434313/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:33 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/config.json proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:33 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN No route matches URI path method=GET module=web path=/telescope/requests proto=HTTP/1.1 remote=[::1]:52494
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN Wasn't expecting STLS here module=pop3 remote=167.94.145.99:42724 session=1
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM ERR -ERR TLS handshake failed read tcp4 144.172.126.97:110->167.94.145.99:42724: read: connection reset by peer module=pop3 remote=167.94.145.99:42724 session=1
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN Failed to send: "-ERR Command STLS is out of sequence" module=pop3 remote=167.94.145.99:42724 session=1
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: 9:46AM WRN Wasn't expecting STLS here module=pop3 remote=167.94.145.99:42724 session=1
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 12 09:46:52 mail.poste.demo.example.comp inbucket[1806804]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x63092a]
Jun 12 09:46:52 mail.poste.demo.example.comp systemd[1]: inbucket.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
      Subject: Unit process exited
      Defined-By: systemd
      Support: https://www.debian.org/support    
      An ExecStart= process belonging to unit inbucket.service has exited.    
      The process' exit code is 'exited' and its exit status is 2.
Jun 12 09:46:52 mail.poste.demo.example.comp systemd[1]: inbucket.service: Failed with result 'exit-code'.
      Subject: Unit failed
      Defined-By: systemd
      Support: https://www.debian.org/support    
      The unit inbucket.service has entered the 'failed' state with result 'exit-code'.

Is it possible inbucket service exited causing STLS  POP3 connection? Thanks.

/lib/systemd/system/inbucket.service content:

[Unit]
Description=Inbucket Disposable Email Service
After=network.target

[Service]
Type=simple
User=daemon
Group=daemon
PermissionsStartOnly=true
Environment=INBUCKET_LOGLEVEL=warn
Environment=INBUCKET_SMTP_ADDR=0.0.0.0:25
Environment=INBUCKET_POP3_ADDR=0.0.0.0:110
Environment=INBUCKET_WEB_ADDR=0.0.0.0:9000
Environment=INBUCKET_WEB_UIDIR=/usr/share/inbucket/ui
Environment=INBUCKET_WEB_GREETINGFILE=/etc/inbucket/greeting.html
Environment=INBUCKET_STORAGE_TYPE=file
Environment=INBUCKET_STORAGE_PARAMS=path:/var/inbucket

#Uncomment line below to use low numbered ports
ExecStartPre=/sbin/setcap 'cap_net_bind_service=+ep' /usr/bin/inbucket
ExecStartPre=/bin/mkdir -p /var/inbucket
ExecStartPre=/bin/chown daemon:daemon /var/inbucket
ExecStart=/usr/bin/inbucket

#Give SMTP connections time to drain
TimeoutStopSec=20
KillMode=mixed
[Install]
WantedBy=multi-user.target
`

**Comment by jhillyerd** [comment]
You definitely hit a bug, even if there was an SSL issue Inbucket shouldn't crash.  Thanks for providing your config, that will help me narrow down the issue.

**Comment by jhillyerd** [comment]
I believe this is fixed, but I'm not sure when I'll release the next beta as I have some incomplete change I'm working on.

In the meantime, if you don't need POP3, you could block the port via firewall.  There isn't a way to disable POP3 via Inbucket's config at present.
