### ISSUE TITLE
Inbucket from scoop fails due to missing index.html

### ISSUE THREAD

**Issue by greenseeker** [inbucket/inbucket#525]
I'm trying to switch from manually copying Inbucket files to Windows servers to installing via Scoop, however, I see the following error during startup:
```
> .\inbucket.exe
...
3:47PM ERR Failed to parse HTML template error="open C:\\ProgramData\\scoop\\apps\\inbucket\\current\\ui\\index.html: The system cannot find the file specified." cwd="C:\\ProgramData\\scoop\\apps\\inbucket\\current" module=web path="C:\\ProgramData\\scoop\\apps\\inbucket\\current\\ui\\index.html" phase=startup
...
```

This is my environment, though I get the same results with the defaults:
```
INBUCKET_LOGLEVEL="debug"
INBUCKET_SMTP_ADDR="127.0.0.1:25"
INBUCKET_SMTP_DOMAIN="staging.lab"
INBUCKET_POP3_ADDR="127.0.0.1:110"
INBUCKET_WEB_ADDR="0.0.0.0:8081"
INBUCKET_STORAGE_TYPE="file"
INBUCKET_STORAGE_PARAMS="path:storage"
INBUCKET_STORAGE_RETENTIONPERIOD="0"
```

If I open the browser page, it just says "Failed to parse HTML template".

If I create C:\ProgramData\scoop\apps\inbucket\current\ui\index.html, then that file is all that's displayed. Even if I go to http://_hostname_:8081/monitor, I only get the index.html file content.

Can I solve this somehow, or is the scoop build busted?

**Comment by jhillyerd** [comment]
It looks like [scoop has an old setting ](https://github.com/ScoopInstaller/Extras/blob/master/bucket/inbucket.json#L20C8-L20C42) for the UI directory:

`"INBUCKET_WEB_UIDIR": "$dir\\ui",`

should probably be

`"INBUCKET_WEB_UIDIR": "$dir\\ui\\dist",`

Perhaps you can check the install dir and make sure ui/dist is present, and try updating the variable if it lets you override it?

**Comment by greenseeker** [comment]
@jhillyerd, thanks for that.

I can override that with the environment variable, and I submitted a bug report with the Extras bucket.
