### ISSUE TITLE
Feature: Spam scoring

### ISSUE THREAD

**Issue by GTB3NW** [inbucket/inbucket#83]
It would be great if a system similar to mail-tester.com was implemented. It could just be an additional button added.

**Comment by jhillyerd** [comment]
I'm not familiar with mail tester, but at first glance it sounds like it tells you how likely it is to be regarded as spam?  Seems like a good idea, and likely within the scope of useful things Inbucket could do.

Similar to #52, this will require Inbucket to be more open to extension than the existing architecture allows.  I am currently working on a huge refactor that will make it easier to do this sort of thing in #69, #79, and #81

**Comment by GTB3NW** [comment]
@jhillyerd It tests mails against spamassassin but also flags issues related to DNS etc, so it makes it easy to resolve issues with DCrDNS and mail server misconfiguration. If you have a server which isn't configured, try mailx to send a mail from command line and it will likely show a plethora of useful information :)
