### ISSUE TITLE
Inbucket Helm Chart

### ISSUE THREAD

**Issue by cpanato** [inbucket/inbucket#97]
@jhillyerd I don't know if this is useful, but I've been working to create a helm chart for inbucket.

if you think this will be good, I can create a PR in the kubernetes/charts to add inbucket in the incubator folder.

otherwise, I will push to my repo only.

thanks!

**Comment by jhillyerd** [comment]
Have yet to use kube for anything, but sounds good to me, go for it.

**Comment by jhillyerd** [comment]
I see the first version got merged, nice!  That looked like quite a bit of work.

Let me know how v1.3 or v2.0 testing goes.

**Comment by cpanato** [comment]
sorry for the delay. was fun to make that. I will try to get familiarized with the new release and I will make the changes in the chart.

I guess we can close this now :)
